pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:aa-lsue/ecocoin.git
          - cd ecocoin.git
          - git push --mirror git@github.com:ChefAharoni/EcoCoin.git
